__author__ = 'mensur'


SQLALCHEMY_DATABASE_URI = "postgresql://registar:registar@localhost:5432/registar"
SQLALCHEMY_ECHO = False


SECURITY_TRACKABLE = True

#SECURITY_REGISTERABLE=True
#SECURITY_CONFIRMABLE=True
#SECURITY_RECOVERABLE=True
#SECURITY_TRACKABLE=True
SECURITY_CHANGEABLE=True

SECURITY_PASSWORD_HASH="pbkdf2_sha512"
SECURITY_PASSWORD_SALT="f24"


